# Generated by Django 4.2.2 on 2025-01-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
