# Generated by Django 4.2.2 on 2025-01-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_premium', 'Can view premium content')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
