# Generated by Django 4.2.2 on 2025-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscriber',
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
    ]
