# Generated by Django 4.2.2 on 2025-01-21 21:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_subscriber_user_is_premium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='в формате +7', max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
