# Generated by Django 4.2.2 on 2025-01-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='users/avatars', verbose_name='Аватар'),
        ),
    ]
