# Generated by Django 4.2.2 on 2025-01-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='creator',
        ),
        migrations.DeleteModel(
            name='SubscriptionUser',
        ),
    ]
